version: '3.9'

services:
  web:
    build:
      context: .
    container_name: django_app
    command: gunicorn IWE.wsgi:application --bind 127.0.0.1:8000
    volumes:
      - .:/app
    ports:
      - "8001:8000"
    environment:
      - DEBUG=True
      - DJANGO_ALLOWED_HOSTS=*
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - CORS_ALLOWED_ORIGINS=http://localhost:3000,http://127.0.0.1:3000
    depends_on:
      - db
      - redis
    networks:
      - django_network

  db:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: django
      POSTGRES_PASSWORD: django_password
      POSTGRES_DB: django_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - django_network

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6380:6379"
    networks:
      - django_network

volumes:
  postgres_data:

networks:
  django_network:

