# Generated by Django 5.1.3 on 2025-04-17 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_alter_category_name_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='can_view_leads',
            field=models.BooleanField(default=False),
        ),
    ]
